### ISSUE TITLE
Exclude filter?

### ISSUE THREAD

**Issue by DaveScream** [SoySauceFor3/log-analysis#2]
What if Im analysing some log and want to exclude strings containing some garbage information that spams log, but want all other lines stay show.  I cant do this with your extension =(

Your extension assume that I know what to look. But its rare and it this cases I can use "find all in open document" feature

**Comment by aepshtin** [comment]
@DaveScream Hi
Do u have any solution?
Maybe we can do this changes in the code? (I have a few more ideas for this extention)

**Comment by JeanTracker** [comment]
@aepshtin 
How about the #7? There is an additional explorer view named **Filter-**.

**Comment by SoySauceFor3** [comment]
Done with ending commit [1dc660e](https://github.com/SoySauceFor3/log-analysis/commit/1dc660e0ac9731525c310945b0d184bdbd3a5eac)
