### ISSUE TITLE
Proposal for UX and Feature Enhancements

### ISSUE THREAD

**Issue by JeanTracker** [SoySauceFor3/log-analysis#7]
@SoySauceFor3 

**Description:**
I have completed the development of the requirements I previously mentioned. As discussed earlier, these changes involve some modifications to the UX design, and I wanted to have a discussion regarding the direction. I have previously contacted you and submitted a [#4 ](https://github.com/SoySauceFor3/log-analysis/pull/4). However, I believe it might be challenging to understand the feature details by submitting them one by one via separate PRs. Therefore, I am sharing the final implementation and requesting your feedback. If you agree with the changes, I will proceed with committing the updates.

Please see the following images and details for reference.
![output](https://github.com/user-attachments/assets/72a967e2-d45f-4873-8c3b-fc02df76e5d6)

**UX Configuration:**

- Primary SideBar: Filter+, Filter-

- Activity Bar: Log Analysis+

**Features:**

- Support for Control Filters by Group: It is inconvenient to control filters one by one. A feature will be added to group filters according to their purpose and control them collectively.

- Support for Managing Groups by Project: Add a feature that allows filters and groups to be managed on project.

- Support for Exclude Filters: Even after applying filters, unnecessary information may still be included. Removing meaningless information would aid in issue analysis.

I look forward to your feedback and hope to collaborate on integrating these enhancements.

Thank you!

**Comment by SoySauceFor3** [comment]
Thanks for the information you provided! The features look pretty cool with us and the mock up (exp the UX) look great! 
We will appreciate if you can send the PRs for the repo to incorporate your implementations. However, for easier review and better roll back precaution, we will appreciate you send a separate PR for each of the features. We look forward to your PRs and thanks for your contribution!

**Comment by JeanTracker** [comment]
@SoySauceFor3 

The resources allocated for improving the extension in a professional capacity are nearly exhausted. I will dedicate personal time to add any additional features moving forward.
